### PR TITLE
Add Lodestar Prater

### LINKED ISSUE #18: Add Lodestar Prater JWT and config to Göerli Nethermind
tracked by https://github.com/dappnode/DNP_DAPPMANAGER/issues/1194

### PR DESCRIPTION
**Pull request by alexpeterson91**
add JWT Secret indexed +1 from Teku's

### CODE REVIEW

**Review by pablomendezroyo — CHANGES_REQUESTED** [review]
Is missing the lodestar in the switch statement https://github.com/dappnode/DAppNodePackage-goerli-nethermind/blob/11427c7363318f629e66cadbccf3f45e63342b75/entrypoint.sh#L3

**Comment by alexpeterson91** [comment]
> Is missing the lodestar in the switch statement https://github.com/dappnode/DAppNodePackage-goerli-nethermind/blob/11427c7363318f629e66cadbccf3f45e63342b75/entrypoint.sh#L3

It needs PRs in all clients and the signer etc, sorry it's a WIP shoulda left as draft.  BTW Is it in the dappmansger for mainnet in the current published version?

**Comment by pablomendezroyo** [comment]
No its not yet. The best thing to do it would be to create an issue in the dappmanager and in every package and link them. Track all of them in the dappmanager issue and mark as resolved when needed

**Comment by alexpeterson91** [comment]
> No its not yet. The best thing to do it would be to create an issue in the dappmanager and in every package and link them. Track all of them in the dappmanager issue and mark as resolved when needed

Will do. I've done it before good way to track wide implementations like new main clients.

**Comment by alexpeterson91** [comment]
Made the issues as tasks in a dappmanger issue transferred them to each relevant repo and just need to do the dsppmaneger still, but have PRs awaiting reviews on all ELs and web3sigber the web3signer likely needs another line to allow lodestar to work with no authentication token. Would appreciate a second set of eyes to make sure I'm not missing anything aside from the auth token issue. @pablomendezroyo

**Review by pablomendezroyo — APPROVED** [review]

**Review by dapplion — APPROVED** [review]

**Pull request merged**
